config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#welcome'
  
  get '/auth/google_oauth2/callback', to:'session#omniauth'

  get '/login', to: 'session#new'
  post 'login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/user/:id', to: 'users#show', as: 'user'

  resources :businesses
  resources :categories, only: [:new, :create]
  resources :neighborhoods do 
  resources :businesses
  end

  resources :users
 
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password

    has_many :businesses
   
    validates :username, :email, presence: true
    validates :username, :email, uniqueness: true

    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.username = auth['info']['name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(16)
        end
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only:[:new, :create]

  def show
   @user = User.find(params[:id])
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      redirect_to businesses_path
    else 
      flash[:messages] = @user.errors.full_messages.join(" - ")
      redirect_to signup_path
    end
  end


  private 

  def user_params 
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end 

end

app/helpers/users_helper.rb
module UsersHelper
    def display_username_header
        if current_user
            "Welcome  #{current_user.username}!"
        end
    end 

end

app/views/users/new.html.erb
<div class = "signup-form">
   
   <div class="login-with-google">
       <%=button_to "Sign up with Google",'/auth/google_oauth2'%>
   </div>
   <h2>Sign Up</h2>  

   <%=form_for @user do |f|%>
      <%=f.label :username%><br>
      <%=f.text_field :username%><br><br>

      <%=f.label :email%><br>
      <%=f.email_field :email%><br><br>

      <%=f.label :password%><br>
      <%=f.password_field :password%><br><br>

      <%=f.label :password_confirmation%><br>
      <%=f.password_field :password_confirmation%><br><br>

      <%=f.submit "Sign Up"%>
   <%end%>

</div>

app/views/users/show.html.erb
<div class="account-page">
    <div class = "user-navbar">
        <%=link_to "Add your business", new_business_path%>
        <%=link_to "See all businesses", businesses_path%>
        <%=link_to "See all nabes", neighborhoods_path%>
    </div>
     <%=image_tag("business-partners.jpg") %>

</div>