config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#welcome'
  
  get '/auth/google_oauth2/callback', to:'session#omniauth'

  get '/login', to: 'session#new'
  post 'login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/user/:id', to: 'users#show', as: 'user'

  resources :businesses
  resources :categories, only: [:new, :create]
  resources :neighborhoods do 
  resources :businesses
  end

  resources :users
 
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
   
    has_many :businesses
    has_many :categories, through: :businesses 

    validates :name, :city, :state, :zipcode, presence: true
    validates :name, uniqueness: {scope: :zipcode, message: "the neighborhood already exist in this zipcode area " }
   

    scope :search_neighborhood, ->(params) {where("LOWER(name) LIKE?","%#{params}%")}
   
    def self.sort_nebe_businesses
         
        neighborhood = Neighborhood.all  
        n = neighborhood.sort_by { |n| n.businesses.size }
        n.reverse
    end 
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

    def index
      if params[:q] && !params[:q].empty?
        @neighborhoods = Neighborhood.search_neighborhood(params[:q])
      else 
        @neighborhoods = Neighborhood.all.alpha_sort
        
      end
    end 

    def new 
      @neighborhood = Neighborhood.new
    end 

    def create 
      @neighborhood = Neighborhood.create(neighborhood_params)
      if @neighborhood.save
        redirect_to neighborhood_path(@neighborhood)
      else 
        render :new
      end
    end 

    def show 
      @neighborhood = Neighborhood.find_by(id: params[:id])
    end 

    def edit 
      @neighborhood = Neighborhood.find_by(id: params[:id])
    end 

    def update 
      @neighborhood = Neighborhood.find_by(id: params[:id])
      @neighborhood.update(neighborhood_params)
      redirect_to neighborhood_path(@neighborhood)
    end 
   

    private 

    def neighborhood_params
      params.require(:neighborhood).permit(:name,:city, :state, :zipcode )
    end 
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
 
end

app/views/neighborhoods/_form.html.erb
<% if @neighborhood.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h3>
 
    <ul>
    <% @neighborhood.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<div class="neighborhood-form">

    <%=form_for @neighborhood do |f|%>
        <%=f.label :name%><br>
        <%=f.text_field :name%><br>

        <%=f.label :city%><br>
        <%=f.text_field :city%><br>

        <%=f.label :state%><br>
        <%=f.text_field :state%><br>

        <%=f.label :zipcode%><br>
        <%=f.text_field :zipcode%><br><br>

        <%=f.submit %><br>
      
    <%end%>

</div>

app/views/neighborhoods/_neighborhood.html.erb
<div class="nabe-info">
    <p><%=@neighborhood.city%></p>
    <p><%=@neighborhood.state%></p>
    <p><%=@neighborhood.zipcode%></p>
</div>

app/views/neighborhoods/edit.html.erb
<h2>Edit Neighborhood</h2>

<%=render "form"%>

app/views/neighborhoods/index.html.erb
<div class ="neighborhood-index">
<div  class = "navbar">
<%=link_to "See all businesses", businesses_path%>
<%=link_to "Add a neighborhood", new_neighborhood_path%>
</div>

<h1>All Neighborhood</h1>
 <div class="search-nabe">
    <%= form_tag('/neighborhoods', method: 'get') do %>
      <%=text_field_tag(:q)%> 
      <%=submit_tag("Search for a neighborhood")%>
    <%end%>
</div>

<div class="all_nabes">
    <%@neighborhoods.each do |n|%>
      <%=link_to "#{n.name}, #{n.city} #{n.state}", neighborhood_path(n)%>
    <%end%>
</div>
</div>
<%=image_tag("residential-houses-exterior-suburb-district_107791-3301.jpg")%>

app/views/neighborhoods/new.html.erb
<div class="neigbor-form-title">
  <h2>Add a new neighborhood:</h2>
</div>

<%=render "form"%>

app/views/neighborhoods/show.html.erb
<div class = "user-navbar">
    <%=link_to "Edit this nabe", edit_neighborhood_path %>
    <%=link_to "Add a business", new_neighborhood_business_path(@neighborhood)%>
    <%=link_to "Back to all neighborhoods", neighborhoods_path%>
    <%=link_to "Back to all businesses", businesses_path%>
</div>
<%if @neighborhood%>
      <h2 class="nabe-name"><%=@neighborhood.name%></h2>
      <%= render "neighborhood"%>
<%if @neighborhood.businesses.empty?%>
       <h5>There is no business listed in this neighborhood, yet!</h5>
<%else%>
   <div class="button-link"> 
      <%=link_to "See all the business in this nabe", neighborhood_businesses_path(@neighborhood), class: "link-for-see-all"%><br><br><br><br>
   </div>  
<%end%>

<%=image_tag "residential-houses-exterior-suburb-district_107791-3301.jpg"%>


  
<%end%>