config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#welcome'
  
  get '/auth/google_oauth2/callback', to:'session#omniauth'

  get '/login', to: 'session#new'
  post 'login', to: 'session#create'
  delete '/logout', to: 'session#destroy'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get '/user/:id', to: 'users#show', as: 'user'

  resources :businesses
  resources :categories, only: [:new, :create]
  resources :neighborhoods do 
  resources :businesses
  end

  resources :users
 
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match '*unmatched', to: 'application#route_not_found', via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <%# <a src= "/">
    <title>NabeB</title>
    </a>
     %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
    
    <% flash.each do |name, msg| -%>
     <div class="error_messages"> <%= content_tag :div, msg, class: name %> </div>
    <% end%>
   
    
  

  <body>

  <h1>NABE B</h1>
  <div class = "display-username">
    <h2><%=display_username_header%></h2>
  </div> 

    <%if logged_in?%>
      <div class="logout-account">
          <%=button_to("Log Out", '/logout', method: 'delete', class: "logout-button")%>
          <%=link_to "Your account", user_path(current_user), class: "delete-button"%>
      </div>
    <%else%>
      <div class="navbar">
        <%=link_to "Home", root_path%>
        <%=link_to "Sign up", signup_path, class: "nav-bar-link"%>
        <%=link_to "Login",login_path,  class: "nav-bar-link" %>
      </div>
    <%end %>
  
    
    <%= yield %>

  </body>
 
  <div class="copyright">2021 	&#169;Claudia Vamesu Halip</div>
</html>